# PostgreSQL
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=app
quarkus.datasource.password=password
quarkus.datasource.jdbc.url=jdbc:postgresql://98.81.134.79:5432/mySchema
quarkus.hibernate-orm.database.generation=update

# Redis
#quarkus.redis.hosts=redis://localhost:6379

kafka.bootstrap.servers=main-nlb-67896e75428b29e0.elb.us-east-1.amazonaws.com:9094

mp.messaging.connector.smallrye-kafka.bootstrap.servers=${kafka.bootstrap.servers}

mp.messaging.outgoing.products-out.connector=smallrye-kafka
mp.messaging.outgoing.products-out.topic=products
mp.messaging.outgoing.products-out.key.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.outgoing.products-out.value.serializer=org.apache.kafka.common.serialization.StringSerializer

mp.messaging.incoming.products-in.connector=smallrye-kafka
mp.messaging.incoming.products-in.topic=products
mp.messaging.incoming.products-in.group.id=quarkus-consumer-group
mp.messaging.incoming.products-in.key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.products-in.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.products-in.auto.offset.reset=earliest

quarkus.http.port=8091
