# PostgreSQL
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/quarkusdb
quarkus.hibernate-orm.database.generation=update

# Redis
quarkus.redis.hosts=redis://localhost:6379

# Kafka
kafka.bootstrap.servers=localhost:9092
mp.messaging.outgoing.products.connector=smallrye-kafka
mp.messaging.outgoing.products.topic=products
mp.messaging.incoming.products-in.connector=smallrye-kafka
mp.messaging.incoming.products-in.topic=products
mp.messaging.incoming.products-in.auto.offset.reset=earliest
