# PostgreSQL
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=app
quarkus.datasource.password=password
quarkus.datasource.jdbc.url=jdbc:postgresql://98.81.134.79:5432/mySchema
quarkus.hibernate-orm.database.generation=update

# Redis
quarkus.redis.hosts=redis://localhost:6379

# Kafka
kafka.bootstrap.servers=main-nlb-67896e75428b29e0.elb.us-east-1.amazonaws.com:9094


quarkus.http.port=8091
